### ISSUE TITLE
Does this support Chart.js

### ISSUE THREAD

**Issue by abishekh** [RelaxedJS/ReLaXed#1]
Hi, I was wondering if this supports [Chart.js](https://www.chartjs.org/) ?

**Comment by Zulko** [comment]
That was actually one of the early ideas, I'll see what I can do. It will certainly work like the current support for vegalite.

**Comment by Zulko** [comment]
Now it does !

**Comment by kilpatty** [comment]
@Zulko would you mind linking to the commit that supports Chart.js? Just want to figure out how to use it :)

**Comment by kilpatty** [comment]
Ah thanks mate :)
