### ISSUE TITLE
Double call JSON.parse

### ISSUE THREAD

**Issue by kexgt** [RelaxedJS/ReLaXed#100]
Hello again :). Why used double call JSON.parse in https://github.com/RelaxedJS/ReLaXed/blob/master/src/index.js#L84
When I send `{"title":"test title"}`, I see error 

> SyntaxError: Unexpected token o in JSON at position 1

But when I remove one call, there is no mistake.

Please tell me, maybe i doing something wrong? Thanks.

**Comment by Zulko** [comment]
Not sure indeed (I haven't tested this feature yet). @Superd22 ?

**Comment by kexgt** [comment]
@Zulko I think double call needed for multidimensional arrays, but my thoughts were not confirmed :)

**Comment by Zulko** [comment]
done.
