### ISSUE TITLE
Absolute reference for include seems to be broken

### ISSUE THREAD

**Issue by nepeckman** [RelaxedJS/ReLaXed#102]
According [the pugjs documentation](https://pugjs.org/language/includes.html), an absolute file reference is a valid path for an `include` statement. However I'm getting an error on the following line:
`include:scss /usr/local/styles/simple-theme.scss`
I'm getting an error stating that `/path/to/working/directory/usr/local/styles/simple-theme.scss` is not a valid file, leading me to believe that the file resolution always attempts a relative path, instead of trying to follow the absolute path. It would be nice to support absolute references, as I'd like to have some different themes available in an easy to reference location in order to reuse them.

**Comment by Zulko** [comment]
Apparently it is because I provide a basedir. But it is unclear whether an absolute path would work without the basedir (since, from the page you linked absolute paths are relative to basedir). What if you use "~/" to start in your homme directory ?

**Comment by nepeckman** [comment]
It still looks relative to the working directory, `path/to/working/directory/~/...`. I see what you're saying about the basedir option though. I guess if the basedir is the root directory, my absolute path would work? But would that mess with other file resolutions?

**Comment by nepeckman** [comment]
If I made a pull request adding a configurable basedir as an option, would you merge it? It'd be nice to have this functionality available for the reasons I mentioned.

**Comment by Zulko** [comment]
wait a bit ill tell you that soon

**Comment by Zulko** [comment]
So I had to change a few things internally but it seems to work. I just pushed a version of ReLaXed in which you can set ``--basedir /`` and then do for instance:

```pug
style
  include:scss /tmp/mystyle.scss
```

**Comment by nepeckman** [comment]
Thanks for addressing this so quickly!
