### ISSUE TITLE
Typo in wiki (config.yaml)

### ISSUE THREAD

**Issue by casrou** [RelaxedJS/ReLaXed#115]
`config.yaml` should be `config.yml`

https://github.com/RelaxedJS/ReLaXed/wiki/Special-file-renderings#equations

Just wanted to let you know, as it caused me some confusion 😐

**Comment by DanielRuf** [comment]
A PR is very welcome.

**Comment by DanielRuf** [comment]
Thanks for letting us know. Do you plan to provide a PR which fixes this?

**Comment by casrou** [comment]
It wouldn't be a problem, but I'm not sure how to make a PR to the wiki.

**Comment by DanielRuf** [comment]
https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

Pointing to the change, repo, commit id and so on should be enough to review and cherry-pick it into the wiki.

**Comment by Zulko** [comment]
thanks for the report @casrou I fixed the typo.

@DanielRuf I have the impression that anyone can edit (or suggest edits) on any wiki just by going to the page and clicking "Edit", even if they don't have push rights on the repo.
