### ISSUE TITLE
Protocol Error @ Page.printToPDF

### ISSUE THREAD

**Issue by ericol** [RelaxedJS/ReLaXed#117]
I'm getting the error below when running relaxed on a simple test file. This is a fresh vagrant box that I installed for relaxed, but I had the same issue in another box that I was using for development.
Node is at version v11.30, npm at 6.4.1

I tried with one of the examples provided and got the same error.

```bash
Launching ReLaXed...

Processing /test.pug...
... HTML generated in 0.1s
... Document loaded in 0.1s
... Network idled in 0.2s
(node:18412) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.printToPDF): Invalid parameters displayHeaderFooter: boolean value expected
    at Promise (/home/vagrant/.nvm/versions/node/v11.3.0/lib/node_modules/relaxedjs/node_modules/puppeteer/lib/Connection.js:186:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/vagrant/.nvm/versions/node/v11.3.0/lib/node_modules/relaxedjs/node_modules/puppeteer/lib/Connection.js:185:12)
    at Page.pdf (/home/vagrant/.nvm/versions/node/v11.3.0/lib/node_modules/relaxedjs/node_modules/puppeteer/lib/Page.js:911:39)
    at Page.<anonymous> (/home/vagrant/.nvm/versions/node/v11.3.0/lib/node_modules/relaxedjs/node_modules/puppeteer/lib/helper.js:145:23)
    at exports.masterToPDF (/home/vagrant/.nvm/versions/node/v11.3.0/lib/node_modules/relaxedjs/src/masterToPDF.js:140:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:18412) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ericol** [comment]
Hi @DanielRuf I fixed it by doing this:
`displayHeaderFooter: !!(header || footer), `
BTW, that was some fast response!!!

**Comment by ericol** [comment]
I'm not well versed in node development, so wwouldn't know how to debug that, thought :(
But that change seemed to do the trick. Just rebooted the vagrant machine (had booted without shared folders) and the generated book looks just fine.

BTW, this is a wonderful project. I love it.

**Comment by ericol** [comment]
@DanielRuf cheers.
Anyway, got it fixed :)

**Comment by Zulko** [comment]
@ericol what example in particular did you try, so we can have a look ? Did you use the latest version on NPM or on Github ?

**Comment by ericol** [comment]
@Zulko I used both the NPM version, and the Github version. The problem boils down to this line of code:
https://github.com/RelaxedJS/ReLaXed/blob/e92cec3dbd94c0246e156d2419e1375839854859/src/masterToPDF.js#L100

I did a first "dirty" installation (I had a Vagrant box that was using for different stuff, but had an old version of node running there, and made a mess of updating it).

Then I installed another box that is prepared for node, `jaxmetalmax/debian8-nodedev`. There I did a few modifications before bringing that up. First I addedthis line to the provision script:

`sudo apt-get install -y libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1`

Changed the installed version of node:

```
nvm install 11.3.0
nvm alias default 11.3.0
```
And finally added relaxed to the list of installed npm packages:

```
npm install -g relaxedjs
```
My first try was with the example you provide with a simple header and paragraph. To rule out it being a problem of missing conf files in the book, then I cloned the examples repo and tried to build [the book](https://github.com/RelaxedJS/ReLaXed-examples/tree/master/examples/book) there, but got the same error.

---

I went back and reverted the change I'd made and added debug as per @DanielRuf suggestions, and this is the result:
```javascript
//console.log(options);
{ path: '/home/vagrant/test/examples/examples/book/book.pdf',
  displayHeaderFooter: '<span></span>',
  headerTemplate: '<span></span>',
  footerTemplate:
   '<style type="text/css">.pdf-footer {\n  font-family: Helvetica;\n  font-size: 10px;\n  width: 100%;\n  text-align: center;\n}  </style><div class="pdf-footer"><span class="pageNumber"></span></div>',
  printBackground: true }
```
As I understand it, the problem is that `options.displayHeaderFooter` should be a boolean and it's a string, as per Puppeteers documentation.

Puppeteer version is 1.11.0

**Comment by DanielRuf** [comment]
One hint:

> nvm install 11.3.0

Better use 10 LTS.

The proposed fix by you should be the correct solution.

Do you want to provide a OR?

**Comment by bussolon** [comment]
I had the same error. I changed `header || footer` in `(header !== '') || (footer !== '')` and solved the problem. I hope this may help.

    // displayHeaderFooter: header || footer,
    displayHeaderFooter: (header !== '') || (footer !== ''),

**Comment by DanielRuf** [comment]
Please see https://github.com/RelaxedJS/ReLaXed/commit/b8fd20c9b6f747b705a2acf1a752ad42d59fd416
