### ISSUE TITLE
VueJS support ?

### ISSUE THREAD

**Issue by abishekh** [RelaxedJS/ReLaXed#121]
Hi,
I'm kinda new to JS and I was wondering if there is a simple way to integrate this functionality into a VueJS based project ? For example, to generate a PDF using certain page elements on the client side.

**Comment by DanielRuf** [comment]
Hi, ReLaXed uses Chrome headless (puppeteer). If you want to provide this feature to users so they have nothing to install, you would have to create this as microservice / webservice with an API.

**Comment by abishekh** [comment]
What if I assume that my page is only supported on Chrome (its kinda already modeled that way for other reasons)?

**Comment by DanielRuf** [comment]
This makes no difference. Just Puppeteer can controls the browser like this.

Otherwise you may need window.print with another script.

**Comment by abishekh** [comment]
ok Thanks :)
