### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by NicolaPez** [RelaxedJS/ReLaXed#123]
```
The command "'relaxed' '/var/www/vhosts/idh-test/var/cache/dev/relaXed/45ca4a15f871c9/letter.pug' '--build-once'" failed.

Exit Code: 1(General error)

Working directory: /var/www/vhosts/idh-test/web

Output:
================


Error Output:
================
/var/www/vhosts/myHost/ReLaXed/src/index.js:119
var updateConfig = async function () {
^^^^^^^^

SyntaxError: Unexpected token function
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.runMain (module.js:611:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:160:9)
```

I have this error, I know that the [doc](https://github.com/RelaxedJS/ReLaXed/wiki/Troubleshooting) says to update node.  My node is already at v10.15.3, and my relaXed at 0.2.1.
someone can help me?

**Comment by Zulko** [comment]
Might be a naive idea, but did you reinstall relaxed after updating Node ?

**Comment by DanielRuf** [comment]
Please upgrade Node.js because `async` is a new feature since Node.js 8.6.

**Comment by DanielRuf** [comment]
Is your Node.js version the global one?

**Comment by NicolaPez** [comment]
My version of Node is global, relaxed not. If I launch 
`npm list -g --depth 0`

I have this

> /usr/local/lib
└── npm@6.4.1

I have installed relaxed in this [way](https://github.com/RelaxedJS/ReLaXed/wiki/Troubleshooting#the-installation-fails).

So, if I launch relaxed from terminal with ec2-user it's run and I have my pdf, if I do from www-data (in this case by a Symfony application) I receive the error I have posted above.

**Comment by DanielRuf** [comment]
What does `where node` on the terminal list?

**Comment by NicolaPez** [comment]
> [ec2-user@ip-10-0-1-67 vhosts]$ whereis node
node: /usr/bin/node /usr/local/bin/node /usr/share/man/man1/node.1.gz

**Comment by DanielRuf** [comment]
What do the following output?

```
/usr/bin/node --version
/usr/local/bin/node --version
```

**Comment by NicolaPez** [comment]
> [ec2-user@ip-10-0-1-67 vhosts]$ /usr/bin/node --version
v6.16.0
[ec2-user@ip-10-0-1-67 vhosts]$ /usr/local/bin/node --version
v10.15.3
[ec2-user@ip-10-0-1-67 vhosts]$

ok, this is the point.

**Comment by DanielRuf** [comment]
Can you symlink to the same binary or update both in some way?

Might work with `su`.

**Comment by NicolaPez** [comment]
Ok, now my user/bin/node is at the right version, and my flux are complete. Thanks for the support!
