### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by DanielRuf** [RelaxedJS/ReLaXed#134]
@Zulko we should bump the version and make a new release

https://github.com/RelaxedJS/ReLaXed/compare/947ba7dbaaf3516a84258d8904768c0879d4d595...master

Also we should tag all the releases t provide them also on GitHub
https://www.npmjs.com/package/relaxedjs?activeTab=versions

Can I do that?

For next release we can use `npm version --patch` which should also create the needed tags.

You may already have the tags locally (see `git tag`). If so you can push them with `git push --tags`.

**Comment by Zulko** [comment]
Done :D

**Comment by DanielRuf** [comment]
Should we also create the previous tags?
