### ISSUE TITLE
Triggering Error: spawn E2BIG on large locals, any work around?

### ISSUE THREAD

**Issue by jonathanasquier** [RelaxedJS/ReLaXed#145]
Hi,
I'm generating large PDFs using dynamically built json locals from a nodejs service, and sometimes I get an `Error: spawn E2BIG` when the json is too large.

Any work around in mind?

Thanks!

**Comment by DanielRuf** [comment]
Hi @jonathanasquier,

Please provide the full stacktrace to see where this error / exception is thrown.

**Comment by jonathanasquier** [comment]
```
error { Error: spawn E2BIG
at ChildProcess.spawn (internal/child_process.js:358:11)
at spawn (child_process.js:533:9)
at /app/relaxed.js:4:19
at buildDeliveryFormFile (/app/index.js:129:11) errno: 'E2BIG', code: 'E2BIG', syscall: 'spawn' }
```
line 4 is:
```js
const relaxed = spawn("relaxed", args);
```
which is in the wrapper i'm calling like this:
```js
    await relaxed(
      template_path,
      output_path,
      "--no-sandbox",
      "--build-once",
      `--temp=${folder_path}`,
      `--locals=${JSON.stringify(data)}`
    );
```

when the json data is huge (I should probably work on that as a start :eye: ) it makes the script crash

**Comment by DanielRuf** [comment]
Well the error comes from the internal child_process module so yes, you have to make it smaller somehow.

We could check if stdin can be also used but such an amount of data is not a normal use case and requires a few changes.

**Comment by jonathanasquier** [comment]
Ok, thanks, I'm going to do more processing on the data before sending it to the template
