### ISSUE TITLE
this._initPDFReader is not a function and ERR_FILE_NOT_FOUND with masterToPDF

### ISSUE THREAD

**Issue by jwmann** [RelaxedJS/ReLaXed#147]
I'm attempting to create a small nodejs server that will take HTML and pass it through relaxedjs and output the PDF.

I'm using the the nodejs example in the README and I'm getting a couple errors:
You can see it here for reference: https://github.com/RelaxedJS/ReLaXed#using-it-as-a-node-module
```
(node:6944) UnhandledPromiseRejectionWarning: TypeError: this._initPDFReader is not a function
    at HTML2PDF.pdf (/Users/jwm/work/app/src/actions/html2pdf.js:35:16)
    at /Users/jwm/work/app/src/router.js:28:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:6944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm using the example almost exactly.
The only difference is I'm take a string of html, and writing to a file and the passing that new html file to HTML2PDF.

The html file is literally just `<span>Hello World</span>`
Of course it seems `this._initPDFReader` isn't actually defined anywhere and I'm not sure what it's even supposed to do so I commented out.

Now the second error doesn't make much sense because I'm getting this error:
```
... HTML generated in 0.0s
net::ERR_FILE_NOT_FOUND at file:temp.html
There was a page loading error.
```

`temp.html` being the path that the temporary html file exists, in-which `masterToPDF` is supposed to write to, except it seems it isn't?

Anybody have similar issues?

**Comment by Zulko** [comment]
I didnt get it. Are you using html2pdf instead of relaxed or with relaxed?

**Comment by jwmann** [comment]
@Zulko I'm creating a class called HTML2PDF just like the example.
It uses the `masterToPDF` function from `relaxedjs`

You can see it for yourself right here:
https://github.com/RelaxedJS/ReLaXed#using-it-as-a-node-module

**Comment by jwmann** [comment]
So I seemed to have fixed the second issue. I believe the temporary html path needs to be an absolute path otherwise it'll fail.

For the first issue I mentioned, it seems that it's not even required?
I just commented it out and it works without it.

If anyone knows what it's meant to do, please reopen this ticket, I'd love to know.
