### ISSUE TITLE
Wanna see my hot pics?💋💋💋

### ISSUE THREAD

**Issue by akdnfbf** [RelaxedJS/ReLaXed#152]
Hi!😻😻😻 Wanna see my hot pics?💋💋💋 Go to this site and find me here. ❤️❤️❤️ My nick is sexygirl662 👇👇👇

https://tinyurl.com/ulpu2gz

**Comment by DanielRuf** [comment]
@Zulko I could need some admin rights to delete or transfer issues =) Maybe you can delete this one.

**Comment by Zulko** [comment]
I don't think I can delete it, I don't see this option anywhere

**Comment by DanielRuf** [comment]
I have this option in my own projects - on the bottom right. Even in issues created by other:

![image](https://user-images.githubusercontent.com/827205/74656136-dbe9e980-518d-11ea-880a-71b99db0d250.png)

**Comment by DanielRuf** [comment]
I have this option in my own projects - on the bottom right. Even in issues created by other users:

![image](https://user-images.githubusercontent.com/827205/74656136-dbe9e980-518d-11ea-880a-71b99db0d250.png)

**Comment by DanielRuf** [comment]
Maybe it works now when it is unlocked.

**Comment by Zulko** [comment]
still not

![image](https://user-images.githubusercontent.com/1646122/74659435-9ed52580-5194-11ea-973b-4c8ce4e888f6.png)
