### ISSUE TITLE
[Question] Only last page footer text is showing with color. Other page footer text is existing but transparent.

### ISSUE THREAD

**Issue by taka66** [RelaxedJS/ReLaXed#178]
First of all, sorry for ambiguous question.
Currently i'm trying to add page footer to show some text and page number.
I'm using `#page-footer` to show page footer.
When I create pdf, last page's footer is OK.
But other pages, seems text is existing but it's transparent.
Does any one know, or see same situation?

https://github.com/RelaxedJS/ReLaXed/blob/master/src/masterToPDF.js#L99

### Last Page
<img width="1109" alt="Screen Shot 2020-03-29 at 19 58 46" src="https://user-images.githubusercontent.com/5513724/77847570-08ffd200-71f9-11ea-8e0a-0402599503ff.png">

### Other Page
<img width="1105" alt="Screen Shot 2020-03-29 at 19 58 33" src="https://user-images.githubusercontent.com/5513724/77847571-0ac99580-71f9-11ea-9a4c-ccf40ca6f3ea.png">

Code to generate footer
```
template#page-footer
  style(type='text/css').
    .pdf-footer {
      -webkit-print-color-adjust: exact;
      display: flex;
      justify-content: space-between;
      font-size: 10px;
      width: 100%;
      margin: 0 0.2in;
      color: #222 !important; /* For Testing */
      /* display: relative; */
    }
  div.pdf-footer
    span #{companyName}
    span #[span.pageNumber]
```

Each pages
```
section.sheet
  p Name - #{test}
  h1 My document's title
  p A paragraph in my document

section.sheet
  p Name - #{test}
  h1 My document's title
  p A paragraph in my document

.sheet {
  page-break-before: always;
}
```

**Comment by DanielRuf** [comment]
Hi @taka66,

We pass the options directly to `page.pdf(options)` of Puppeteer so this might be an issue with Puppeteer.

See https://github.com/puppeteer/puppeteer/search?q=footer+transparent&type=Issues

**Comment by taka66** [comment]
@DanielRuf Hi. Daniel. Thanks for the info. And I found https://github.com/puppeteer/puppeteer/issues/4738
is almost same situation for this issue.

When I added enough margin in `@page` , i can see footer properly.

```
@page {
  margin-bottom: 1cm;
}
```

Thanks🙇‍♂️
