### ISSUE TITLE
Using relaxedjs as a node module in AWS and run once

### ISSUE THREAD

**Issue by MageCoder** [RelaxedJS/ReLaXed#180]
I would like to use relaxedjs as node module in AWS lambda.
How can i run the code only one time?
Tryed to add --build-once to pupeteer config or relaxed globals, but didnt work.

Any hints?

THX

**Comment by DanielRuf** [comment]
Hi @MageCoder,

Please provide the code tgat you use.

It should build once by default afaik.

https://github.com/RelaxedJS/ReLaXed/blob/master/README.md#using-it-as-a-node-module

**Comment by MageCoder** [comment]
Could fix that problem by myself.
Did it that way

https://github.com/MageCoder/relaxedJsPoc/blob/master/index.js
