### ISSUE TITLE
Please publish current version (0.2.5) to npmjs.com

### ISSUE THREAD

**Issue by kabomi** [RelaxedJS/ReLaXed#199]
Hello,

since 4 months there is version 0.2.5 (package.json). Could someone (admin) please publish the package. This will solve a lot of dependency issues.

<img width="366" alt="grafik" src="https://user-images.githubusercontent.com/3160460/183067824-ecd267d9-a95a-450a-887c-f50bbe1c4819.png">

Thank you a lot! 
@Flakebi  @Zulko

**Comment by Zulko** [comment]
With apologies for the slowness, version 0.2.5 is now published on npm.
