### ISSUE TITLE
Feature to generate pdf on first call

### ISSUE THREAD

**Issue by abishekh** [RelaxedJS/ReLaXed#2]
Hi,
The tool works great with the recommended atom setup. I was wondering if there was a way to make it generate the pdf given an html file without having to go in and save the file atleast once?

**Comment by Zulko** [comment]
Hey, it's in the plans, even though I am not quite sure yet how to combine javascript's async and a one-off terminal command

**Comment by Zulko** [comment]
v0.1.4 now has a --build-once option:

```
relaxed mydocument.pug --build-once
```

**Comment by abishekh** [comment]
Thats amazing! Thanks.
