### ISSUE TITLE
EPub

### ISSUE THREAD

**Issue by Immortalin** [RelaxedJS/ReLaXed#3]
If ReLaXed can export EPub, that would be truly wonderful. EPub is basically XHTML + assets + some metadata in a Zip file

**Comment by Zulko** [comment]
What would be the advantage of ReLaXed compared to e.g. Pandoc or other tools that can make epubs ?

**Comment by Zulko** [comment]
closing this as unclear why relaxed would be advantageous for epubs, compared with other tools that already do that.
