### ISSUE TITLE
proposal: unit tests

### ISSUE THREAD

**Issue by DanielRuf** [RelaxedJS/ReLaXed#30]
We need unit tests which can be run with Travis CI on every PR and commit to catch issues early.

**Comment by Zulko** [comment]
Oh yeah, I was going to create that issue :)

I'm not sure what the best framework for this would be, but testing the CLI (not the internal JS) would be the most rewarding first step.

The travis script would first install NPM/ReLaXed, then a script would mechanize the use of the CLI and check for some elements in the generated PDF. I don't know what the best test framework for this is. It would be just me I would write a Python script, but not sure what else exists out there.

**Comment by DanielRuf** [comment]
puppeteer + jest / (mocha +chai) probably like we already use at zurb/foundation-sites and was proposed by me in other projects and works good so far.

**Comment by DanielRuf** [comment]
> The travis script would first install NPM/ReLaXed, then a script would mechanize the use of the CLI and check for some elements in the generated PDF. I don't know what the best test framework for this is. It would be just me I would write a Python script, but not sure what else exists out there.

Travis and others checkout the repo and we normally directly call / execute the scripts using node or npm (comes preinstalled with their setup because of nvm).

**Comment by benperiton** [comment]
Just thinking aloud here, but could we use something similar to jest snapshots for testing PDF output? So have a reference image and then compare that against the generated PDF to check for Chromium changes

**Comment by DanielRuf** [comment]
> Just thinking aloud here, but could we use something similar to jest snapshots for testing PDF output? So have a reference image and then compare that against the generated PDF to check for Chromium changes

This should be possible. You mean visual regression tests if I understand correctly.

**Comment by Zulko** [comment]
@benperiton yes but in this case lets put the screenshots in a separate repository. I'm not sure how much efforts should go into the test suite (vs. developing new features)

 In early stages we would just need the bare minimum, a test that shows that ReLaXed can run in the command line under various options and generates files with the expected sizes at the right places. That would be already enough to make sure PRs dont break the software.

**Comment by benperiton** [comment]
@DanielRuf Exactly, to me having visual regression tests makes sense for something that generates a PDF output - which users would expect to be the same when updating.

@Zulko I see your point, perhaps locking the puppeteer version for the moment would be best? That way there wouldn't be issues coming in for layout changes if/when chromium gets updated.

**Comment by Zulko** [comment]
I have set up a test suite where we can provide document templates and expected PNG outputs and if the test computes a diff image, which should be practical enough to troubleshoot.

At the moment the tests only generate the examples with ``--build-once`` and do not test the various command line options or custom file generations (plots, tables, etc.). But i consider it enough to close that generic issue for now.
