### ISSUE TITLE
Do you support other languages?

### ISSUE THREAD

**Issue by TimKrowder** [RelaxedJS/ReLaXed#32]
What can I do to make it support Chinese without making error?
`` C:\\Users\\***\\Desktop\\my_document.pug:3:1
  > 1| h1 My document's title
  > 2| p A paragraph in my document
  > 3| ��ã��������ˣ�
-------^

unexpected text "��ã��"
There was a Pug error (see above)
... done in 0.01s

**Comment by DanielRuf** [comment]
Hi, is your file utf8 encoded? Can you share a sample source file with us with which we can reproduce it on our side?

**Comment by TimKrowder** [comment]
Close it, close it... I wrote the wrong grammar.
