### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by evanlihou** [RelaxedJS/ReLaXed#33]
OS: macOS 10.13.5
NPM: 4.6.1
Relaxed version: 0.1.2 (according to NPM)

Error occurs when trying to run the "relaxed {filename}" command
```
Error: Cannot find module 'perf_hooks'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/relaxedjs/src/index.js:6:25)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by Zulko** [comment]
ReLaXed requires a more recent version of Node, not sure yet what the minimal version is. Can you [upgrade npm](https://davidwalsh.name/upgrade-nodejs) and try again ?

**Comment by evanlihou** [comment]
Thanks for the info. I believe I stayed on NPM 4 due to React (Native I think) not supporting 5 but I’ll try it

**Comment by evanlihou** [comment]
Update: Upgraded to NPM 6.0.0 with node 10.0.0 and am still experiencing the same issue.

**Comment by Zulko** [comment]
weird. Are you sure that your node binary has been updated ? This worked a few days ago with #7 (see the 4th message)

**Comment by evanlihou** [comment]
That seems to have fixed it. For help to anyone else: I updated npm which brought Node up to 10.0.0, but perf_hooks didn't seem to update until I specifically did `npm i -g node`

Thanks for the help!

**Comment by DanielRuf** [comment]
Just fotr your information, npm and node are two different "dependencies" and you can always upgrade / downgrade one of both using nvm, npm, nodenv and so on.

**Comment by DanielRuf** [comment]
In some cases you have to reload your environment using `source ~/.zshrc` or similar.
