### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by carsonjones** [RelaxedJS/ReLaXed#34]
OS: macOS 10.13.3
NODE: v7.9.0
NPM: v4.2.0
Relaxed version: 0.1.2 (according to NPM)

Error occurs when installing `npm install -g relaxedjs`

```
➜ npm install -g relaxedjs
npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "-g" "relaxedjs"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/carson/.npm/_logs/2018-05-07T14_50_08_755Z-debug.log

```

Any ideas?

**Comment by Zulko** [comment]
Is that the full error ? Have you tried upgrading Node or NPM to a more recent version ?

**Comment by DanielRuf** [comment]
Definitely sounds like a npm error.

**Comment by carsonjones** [comment]
Let me check and will report back. Thanks for the help!

**Comment by carsonjones** [comment]
Looks like I had a problem locally with my npm registry.

I ran 

```
npm set registry https://registry.npmjs.org/
```

and everything is now working fine. Thank you!
