### ISSUE TITLE
Document Signatures

### ISSUE THREAD

**Issue by KrishnaPG** [RelaxedJS/ReLaXed#36]
How to generate digitally signed documents?

**Comment by DanielRuf** [comment]
Hi, this is not supported by RePaXed (out of its scope) and normally requires a certificate or PGP key and some hashing solution in the library.

Adobe Acrobat and PDFX support this.

**Comment by Zulko** [comment]
PDFs are generated with chromium so we would need chromium to be able to generate signed documents before we can propose that on our end (does that make sense ?)

**Comment by Zulko** [comment]
Seems indeed difficult to do, so closing this one. Feel free to reopen if I missed an obvious way to do so.

**Comment by Zulko** [comment]
Sorry for the noise, but just after writing this I realized that some libraries can do it. I don't want to have this as a core feature, because all these libraries require to install non-JS platform-specific software, but they could be added as plugins adding a "post-pdf-generation" hook.

**Comment by DanielRuf** [comment]
> could be added as plugins

Definitely. This should be the core here and signatures and other things can be added as plugins.
