### ISSUE TITLE
Refactor out Nodejs related code so it can run in browser

### ISSUE THREAD

**Issue by linonetwo** [RelaxedJS/ReLaXed#38]
See https://stackblitz.com/, it's possible to run a dev server and an editor in the browser's service worker.

I think it's possible to build an online ReLaXed editor if all nodejs related code is refactored out.

**Comment by Zulko** [comment]
but will it be able to generate PDFs ?

**Comment by linonetwo** [comment]
I guess iFrame will work.
```js
iframe.focus();
iframe.contentWindow.print();
```
Let me try out.

**Comment by linonetwo** [comment]
Maybe one day, author of paper only need to send a link to his editor.

**Comment by Zulko** [comment]
Do you know overleaf ? Its basically that, but for latex

**Comment by linonetwo** [comment]
It will be different if we are using web technology.
Overleaf may be running their server, but with ReLaXed, it can be serverless. 

~~Even the storage can use ipfs.~~

**Comment by Zulko** [comment]
Definitely something I want to explore, but it would be quite a different project, and at the moment I dont like that the user would need to go through the print-page interface, possibly redefining paper size etc. everytime. It would also be some work to let users manage file and assets in their browser. Other drawbacks would be that you couldnt edit an image file in gimp/inkscape, and see real-time changes in your PDF.

But I agree that it would be orders of magnitude more accessible than the current solution.

**Comment by DanielRuf** [comment]
I think it should be still standalone and available as Node.js solution with headless Chrome (puppeteer) in the background.

Personally I see not much sense in migrating the codebase and let this run in all browsers.
IF you start supporting one you have to support them all probably.

**Comment by Zulko** [comment]
One good aspect would be user conversion, since you could get started on an example in seconds, nothing to install. You could also make a custom UI with relaxed-specific features. But yeah, huge project.

**Comment by DanielRuf** [comment]
> One good aspect would be user conversion, since you could get started on an example in seconds, nothing to install. You could also make a custom UI with relaxed-specific features. But yeah, huge project.

Could be easily done with React which can run Node.js code in the background and consume Node.js modules.

So basically we have a feature request for a different implementation (which needs proper planning and evaulation of possible solutions).

**Comment by Zulko** [comment]
...with the problem that the main feature (automatic PDF generation with custom margins, footers, headers, etc.) is certainly not doable from a browser.

**Comment by linonetwo** [comment]
Let me close this till there are out-of-box solutions to manage folders of assets in service worker(like [stackblitz-core](https://github.com/stackblitz/core)), html-to-pdf generator (maybe [pdfjs](https://rawgit.com/MrRio/jsPDF/master/docs/plugins_addhtml.js.html) but doc said it's deprecated) and assert editors (for images).
