### ISSUE TITLE
Expose an API the way pug does (compile, render...)

### ISSUE THREAD

**Issue by jonathanasquier** [RelaxedJS/ReLaXed#41]
I'd love to use relaxed within a node script, should we expect a callback/promise API?
thanks!

**Comment by DanielRuf** [comment]
You can probably use shelljs or shx to run and wait for when the execution has finished.

**Comment by Zulko** [comment]
I believe you can access the main "pug_to_pdf" function [here](https://github.com/RelaxedJS/ReLaXed/blob/e15544dfb38625eaf369610809e627d36d9d93d5/src/converters.js#L151) but you need to provide to it a ``page`` which is basically an open Chromium thumbnail.

**Comment by jonathanasquier** [comment]
I went for DanielRuf's solution
