### ISSUE TITLE
getting-started Demo Fail ❌

### ISSUE THREAD

**Issue by chinanf-boy** [RelaxedJS/ReLaXed#42]
https://github.com/RelaxedJS/ReLaXed#getting-started

#### I follow the steps

---
### Default term with zsh

``` bash
❯ relaxed dd.pug
Watching dd.pug and its directory tree.

Processing detected change in /dd.pug...
File load error: file:///***/n/lib/node_modules/relaxedjs/node_modules/mathjax/unpacked/jax/output/SVG/jax.js
File load error: file:///***/n/lib/node_modules/relaxedjs/node_modules/mathjax/unpacked/jax/output/SVG/fonts/TeX/fontdata.js
File load error: file:///***/n/lib/node_modules/relaxedjs/node_modules/mathjax/unpacked/jax/input/AsciiMath/jax.js
```

### ReLaXed Examples

I try the https://github.com/RelaxedJS/ReLaXed-examples

It Work!!! , `but I cannot create a new PDF with My own *.pug`

**Comment by benperiton** [comment]
When you say "I cannot create a new PDF with My own *.pug" what error(s) do you get?

**Comment by chinanf-boy** [comment]
I try the https://github.com/RelaxedJS/ReLaXed#getting-started Demo

```
❯ relaxed dd.pug
Watching dd.pug and its directory tree.

Processing detected change in /dd.pug...
File load error: file:///***/n/lib/node_modules/relaxedjs/node_modules/mathjax/unpacked/jax/output/SVG/jax.js
File load error: file:///***/n/lib/node_modules/relaxedjs/node_modules/mathjax/unpacked/jax/output/SVG/fonts/TeX/fontdata.js
File load error: file:///***/n/lib/node_modules/relaxedjs/node_modules/mathjax/unpacked/jax/input/AsciiMath/jax.js
```

### File load error

**Comment by benperiton** [comment]
Ah, sorry I misunderstood :)

What version of node/npm are you using?

**Comment by chinanf-boy** [comment]
```
~
❯ node -v           
v9.6.1

~
❯ npm -v                          
6.0.0
```

**Comment by benperiton** [comment]
Just to check, you installed using ```npm i -g relaxedjs``` without using sudo?
I'm a bit stumped, that error seems to be coming from mathjax itself

**Comment by chinanf-boy** [comment]
My node install by https://github.com/tj/n

node install Dont need the `sudo`

May be I try use the sudo node try again

**Comment by chinanf-boy** [comment]
>So weird

## Try one:

0. `cd $HOME`
1. `sudo/no relaxed dd.pug`
❌

## Try two:

0. `where relaxed`
1. `cd relaxed PATH`
2. `sudo/no node src/index.js dd.pug`
✅

**Comment by chinanf-boy** [comment]
`sudo/no` is say : I `use sudo` and `no use` both
