### ISSUE TITLE
What I should know to use ReLaXed and other questions about the pug syntax.

### ISSUE THREAD

**Issue by adamryczkowski** [RelaxedJS/ReLaXed#43]
I am a data scientist that considers writing a library for R that will offer an alternative document generation pipeline that would replace the usual path of `R -> pander -> pandoc -> xelatex -> pdf`. Unfortunately, in short, I have never written anything to be executed directly by the Web browser. I don't program in JavaScript and I barely know what CSS is for. (I am familiar with the idea of having nested style hierarchy; I simply never used a CSS implementation of it. )

I know LaTeX and I spent a great deal of time writing or gluing together different document rendering systems for use with the statistical output.

1. What path should I take learn how to efficiently use ReLaXed (and pug) for scientific data reporting?

The first paragraph on the Pug's "Getting Started" page says

> The general rendering process of Pug is simple. `pug.compile()` will compile the Pug source code into a JavaScript function that takes a data object (called “locals”) as an argument.

2. I understand, that the `pug.compile()` is a JavaScript call. Do I need to learn JavaScript to use the ReLaXed? Does a `pug` file format actually follows a JavaScript syntax (like JSON), but then what happened to the semicolons?

3. What is the minimal Hello World document in ReLaXed? Is it `p Hello World!`? If so, why you never use the syntax `p <text>` in the examples? (The closest I can find is `p.\n<paragraph text>`).

4. The source `pug` files have lines that start with coma, like `.main-text` or `.title`. The dot before `.main-text` and a nested structure present in some pug files suggests it is a property call of some default "root-document" object, but it is only my guess. What is the name of words that are prefixed by the comma? Where can I look up the meaning of them?

5. There are lines that are prefixed with a colon, like `:markdown-it(html=true)`. Is it also some sort of property call, (perhaps for a static member, like in C++)?

6. Some lines start neither with coma nor colon, like `style` or `h1#title Beautiful PDF documents with web technologies`. What is the difference between them and the lines prefixed with `.` and `:`?

7. You seem to use `#` for something like the separation between a keyword and its arguments, like in `h1#title Beautiful PDF documents with web technologies` or `td.positive #[i.icon.checkmark] Totally working`. Am I right? (If not, what is the meaning of the `#`?)

8. All the `pug` documents in the examples are nicely indented with spaces. Do spaces have a syntactic meaning, like in Python, or are they simply there for readability, like in C or JavaScript?

**Comment by Zulko** [comment]
Question (1) that's actually a good question. Relaxed can react to changes in files so you could make documents with figures and your whole PDF will auto-update when your figures get regenerated. Plus, you can print nicely-highlighted code.
 I am also in scientific computing and for now I stick to the standards (google doc etc.) for quick and easy report, but if I had to do the same kind of reports again and again, ReLaXed could be a solution.

for (2) you wouldnt need to worry about knowing javascript (but you could inject some javascript in your documents).

For questions (3, 4, 6, 7, 8) you will find the answers on the Pug website. Pug is quite easy to learn, it is really just another way to write HTML (for instance ``#title My title`` is equivalent to ``<div id="title"> My title</dic>``), so you need some knowledge of HTML. In short: ``#title`` is a div with an ID, ``.title`` is a div with a class, ``:markdown`` means you are going to filter (i.e. transform) everything below,

**Comment by Zulko** [comment]
note: ReLaXed could be a good choice for making data reports in general, but NOT a good choice to be a dependency of a R library. Mixing some Node/JS dependencies in a R library could be difficult.

**Comment by adamryczkowski** [comment]
>note: ReLaXed could be a good choice for making data reports in general, but NOT a good choice to be a dependency of a R library. Mixing some Node/JS dependencies in a R library could be difficult.

Yes, but there is no other way to do that. We already use pandoc as a dependency for report generation and right now it is fairly well-entrenched practice.

**Comment by Zulko** [comment]
In that case, the simplest is to ditch R for Python :stuck_out_tongue: 

I am closing this as ReLaXed is meant to be used interactively as a desktop application, and cannot be easily bound to R. But I'll make a "Scientific Report" example when I can, highlighting figures, code highlight, etc.

**Comment by Zulko** [comment]
What you can do with ReLaXed is only as good as your HTML/CSS skills. It takes baby steps. If more people contribute to new templates, it will make your life easier.
