### ISSUE TITLE
Programmatically generate PDF

### ISSUE THREAD

**Issue by bwobst** [RelaxedJS/ReLaXed#52]
I'd like to use this in an AWS Lambda function; however, I need to invoke the PDF generation once, not watch a directory for changes. I wasn't able to find anything in the docs. Is this possible?

**Comment by Zulko** [comment]
Thay will be possible at the next release. Can i ask what is your use case ?

**Comment by DanielRuf** [comment]
Hm, I wonder if `touch` could trigger a change.

**Comment by DanielRuf** [comment]
I guess he wants to use it as microservice for a custom webservice and needs this (which makes much sense) and it's a good usecase =)

**Comment by Zulko** [comment]
Yes but in this case what would make sense would be a server which keeps a chromium instance open and renders documents on request. It would be way faster than starting over every time. And i believe such servers already exist out there. The only advantage of ReLaXed in this case is the Pug/SCSS/mathjax support.

**Comment by DanielRuf** [comment]
Right. Would be interesting to know how the pervormance of the Lambda function is compared to similar solutions and what could be improved to solve bottlenecks for bigger applications and solutions.

**Comment by Zulko** [comment]
Fixed in v0.1.4 which now has a ``--build-once`` option:

```
relaxed mydocument.pug --build-once
```

**Comment by DanielRuf** [comment]
@thedewpoint sure, with the new flag you can easily build such a microservice.

**Comment by nicholasjconn** [comment]
If I were to use a Lambda function on AWS to generate a PDF report programmatically, does RelaxedJS still require a Chromium instance? Specifically, is it possible to have the full functionality for generating a PDF from just code embedded in Lambda without any external servers/instances/services?

**Comment by DanielRuf** [comment]
> If I were to use a Lambda function on AWS to generate a PDF report programmatically, does RelaxedJS still require a Chromium instance? Specifically, is it possible to have the full functionality for generating a PDF from just code embedded in Lambda without any external servers/instances/services?

Yes, as the PDF method of Puppeteer is used which uses a headless Chromium instance.
