### ISSUE TITLE
How can i make pdf by dynamic html content?

### ISSUE THREAD

**Issue by awesomehimanshu** [RelaxedJS/ReLaXed#54]
I have seen approach you use .

If i give html it convert html to pdf and applied all css in it automatically .

Let say i want the pdf on fly.

I have a variable in node.js.

var htmlContent = "<html><body>somemorehtml</body></html";

and i want to generate pdf by this does , it is possible or Relaxedjs need the static content only.

Thanks. LET ME KNOW IF ANY INFO NEEDED

**Comment by Zulko** [comment]
ReLaXed relies on puppeteer for generating PDFs from HTML. You should check it out, Puppeteer makes it as easy as:

```javascript
await page.setContent(html)
await page.pdf(path: 'mydoc.pdf')
```

**Comment by awesomehimanshu** [comment]
That means if i want to generate pdf dynamically from node.js code . I have to use Puppeteer  instead of ReLaXedJS.  ReLaXedJS only works for static content on the directory .

**Comment by Zulko** [comment]
Yes. It also adds some features (support for pug, scss, diagrams, etc.).

To be exact, you could use ReLaXed from Node by writting your files to the disc and then, from Node, calling ReLaXed on these files. But it would be overkill if you can use Puppeteer for your usecase.

**Comment by awesomehimanshu** [comment]
thanks man . Appreciate the quick response .
