### ISSUE TITLE
[Discuss] Maybe we can use react or jsx as DSL

### ISSUE THREAD

**Issue by stephenkingsley** [RelaxedJS/ReLaXed#56]
In my opinions, there is not many people use `pugjs`. And maybe we can use react as second choose. We can write some logic code, like below

```js
const mockData = [{ name: 'stephen', sex: 'male', age: 25 }, { name: 'stephen', sex: 'male', age: 25 }, { name: 'stephen', sex: 'male', age: 25 }, { name: 'stephen', sex: 'male', age: 25 }];

const Item = props => (
  <div>
    <p>name: {props.name}</p>
    <p>sex: {props.male}</p>
    <p>age: {props.age}</p>
  </div>
);

const List = props => (
  <div>
    { mockData.map((item, index) => <Item name={item.name} male={item.male} age={item.age} key={index} />) }
  </div>
);
```
That is more powerful than just HTML, and can provide kinds of scenes to use.

**Comment by Zulko** [comment]
This sounds like a completely different project, with different objectives, a different stack, etc. the only common part with the current project would be the pdf generation with pupetteer, and that's 3 lines. I totally get the appeal though, I'd do one based on Vue if I had time. But by proposing  REACT as a framework you are restricting the software to hardcore frontend developers. Pug, on the other hand, has nothing scary about it, anyone with a bit of HTML experience can get started on making documents with it.

**Comment by DanielRuf** [comment]
There is already react-pdf or similar. I would also say that this is too much for ReLaXed.

**Comment by DanielRuf** [comment]
In general, you can use anything in your HTML and ReLaXed will render it.

**Comment by Calinou** [comment]
Should this issue be closed? It seems there's no consensus on adding this feature.

**Comment by Zulko** [comment]
It seems that there is a consensus not to add the feature, closing.
