### ISSUE TITLE
Failed to use  on mint Linux :(

### ISSUE THREAD

**Issue by yueguangguang** [RelaxedJS/ReLaXed#58]
When I use the ReLaXed on  mint linux 18.3 after all npm dependencies have been installed,it throws an error 
```➜  pdf2web relaxed 11.pug
Watching 11.pug and its directory tree.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: no space left on device, watch '/home/yue/pdf2web/ReLaXed/node_modules/ajv/lib/dotjs/README.md'
    at FSWatcher.start (fs.js:1389:26)
    at Object.fs.watch (fs.js:1426:11)
    at createFsWatchInstance (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/lib/nodefs-handler.js:229:14)
    at FSWatcher.NodeFsHandler._handleFile (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/lib/nodefs-handler.js:256:21)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/lib/nodefs-handler.js:474:21)
    at FSReqWrap.oncomplete (fs.js:166:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/usr/lib/node_modules/relaxedjs/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:166:5)
```
But when I use the command `df -h`,I found that my system still has a lot of space。
```df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G   18M  1.6G   2% /run
/dev/sdb4       189G   17G  163G  10% /
tmpfs           7.8G   37M  7.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/sda1        99M   48M   52M  48% /boot/efi
/dev/sdb5       115G   16G   94G  15% /home
cgmfs           100K     0  100K   0% /run/cgmanager/fs
tmpfs           1.6G   40K  1.6G   1% /run/user/1000
```
After that,I update` max_user_watches `to solve  the same problem from [https://stackoverflow.com/questions/22475849/node-js-error-enospc](https://stackoverflow.com/questions/22475849/node-js-error-enospc).However,It did not solve the problem.And the ReLaXed Into an endless wait, did not return success or error。
```
➜  pdf2web relaxed 11.pug 
Watching 11.pug and its directory tree.
```
I also try to run ReLaXed with root privileges,but it still no change in the above situation.On the other hand,I has ensured the correct chromium version has been downloaded and configured correctly in index.js.
:( I don't have any ideas so I hope to turn to you

**Comment by DanielRuf** [comment]
Hi, what Node.js version do you use?

**Comment by DanielRuf** [comment]
See https://stackoverflow.com/questions/22475849/node-js-error-enospc and check the answers (tmp, sysconfig, ...).

**Comment by yueguangguang** [comment]
I am sorry to reply you so late，When I create issus, the version  I use are 10.1 of node.js and 5.6 of npm.After writing the issus ,I create a virtual machine which has the same linux  environment to test another environment .In the VM ,The nodejs version I use is 8.11.2.
However,The same problem has arisen again.The ReLaXed Into an endless wait, did not return success or error.Waited for a long time without the next response and prompt,Just show this sentence `Watching test.pug and its directory tree.`I tried to install nodejs by soft-linking the pre-compiled installation package. At the same time, I tried to install apt-get and the results were the same.

On the other hand, In my windows10 operating system, there is also the problem of waiting for a long time to respond, and only the phrase `Watching test.pug and its directory tree.`
In both environments, I have set the tmp directory to a new directory with enough space to read and write.
:(

**Comment by yueguangguang** [comment]
I'm not particularly familiar with node.js and npm. I wonder if it's pupeteeer that has problems with some settings? I immediately puppeteer for some basic tests.

**Comment by Zulko** [comment]
This is the expected behaviour. It is watching the directory and will render when a file changes in the directory. If you want to build directly, from v0.1.4 (released yesterday) use option --build-once at the end of your command

**Comment by yueguangguang** [comment]
@Zulko Thank you for your doubts, according to what you said I have been able to use ReLaXed perfectly, I'm very sorry for the interruption to the two developers.

**Comment by Zulko** [comment]
No problem at all, at this early stage any feedback is much appreciated.

**Comment by DanielRuf** [comment]
> @Zulko Thank you for your answer, according to what you said I have been able to use ReLaXed perfectly, I'm very sorry for the interruption to the two developers.

There is no reason to be sorry. Any feedback is welcome and helpful like @Zulko already wrote.
