### ISSUE TITLE
Can this be run from the browser?

### ISSUE THREAD

**Issue by r-tock** [RelaxedJS/ReLaXed#6]

**Comment by crubier** [comment]
That would be NICE

**Comment by Zulko** [comment]
It would be nice, but I see several obstacles, so the closest you can come to that is [the recommanded Atom setup](https://github.com/RelaxedJS/ReLaXed/wiki/Tips-and-recommendations#recommended-editing-software).

Some problems with in-browser runs:

- Browsers can't print PDFs on demand via javascript, you need user action for that. There are ways to generate PDFs from the browser, but they are not as good as Chrome's PDF printing of webpages.
- If there were ways to force the browser to print PDFs, you would still have the problem that different browsers would print slightly different versions so you would have sources for your documents that are "compatible with chrome but not with safari".
- ReLaXed reacts to file changes on your machine (every time a picture changes for instance, the document is regenerated). This allows you to edit an image with Gimp or an SVG with Inkscape and see changes in real time in your PDF. You couldn't do that from inside a browser (as browsers are insulated from your file system).

**Comment by Zulko** [comment]
Closing this as it certainly wont be doable any time soon.

**Comment by crubier** [comment]
Right now I use [react-pdf](http://react-pdf.diegomura.com/repl) , which works very nicely from the browser, using [pdfkit](http://pdfkit.org/) but is missing some features. I was hoping that relaxed could adress those, but ok.

**Comment by joallard** [comment]
If anyone found a decent solution to this, please let me know!

**Comment by crubier** [comment]
@joallard  We just use puppeteer or playwright to print HTML pages as PDF.

**Comment by Zulko** [comment]
@crubier do these run from the browser?

**Comment by crubier** [comment]
No but from the browser, we just use normal HTML, and [react-to-print](https://www.npmjs.com/package/react-to-print) to print it as PDF. Basically nowadays all browsers support print to PDF, so PDF generation in JS is not that useful. Just make the html you want and print it as PDF.
