### ISSUE TITLE
Broken colors.

### ISSUE THREAD

**Issue by Drew-S** [RelaxedJS/ReLaXed#66]
Since we integrated *citation-js* the *colors* package appears to have been broken by *citation-js*. Not sure why, but instead of a bold output in the terminal like it should, I am getting `[Function] bold`. Everything else by *colors* still works though.

I would like to recommend a switch to *[signale](https://github.com/klauscfhq/signale)* instead of *colors*. Personally, I prefer the way it looks, plus *citation-js* does not interfere.

![image](https://user-images.githubusercontent.com/15166463/40569919-f9cba95e-6042-11e8-8d9a-c333ee7ffd9d.png)

The `[set] Unknown property: P407` is an issue with *citation-js* and wikidata entries. Currently *citation-js* does not have (or know) how to parse that property, so that will show up every time someone uses a wikidata entry, which my example does use. And, I am unaware of a way to suppress *citation-js* from logging that information.

**Comment by Zulko** [comment]
I've seen that and my last commit fixes it (just pull from master). But yeah signale looks great.

**Comment by Drew-S** [comment]
Well that is good that it is no longer broken, still odd that `citation-js` does that.

**Comment by Zulko** [comment]
note that there is also "chalk.js" which does the same as "colors" but has more stars on github, but i am unsure why.

**Comment by DanielRuf** [comment]
`chalk` is widely adopted and often better than `colors` and is better maintained (my experience).
