### ISSUE TITLE
Create PDF right away, even when `relaxed` command is run without `build-once` command.

### ISSUE THREAD

**Issue by 1AmNegan** [RelaxedJS/ReLaXed#67]
If _my_document.pug_ already exists and a user wants to edit this file, it would be more intuitive to create _my_document.pdf_ as soon as the user runs `relaxed my_document.pug`, instead of watching for the file to change and then creating the pdf. 

This would help the user to first take a look at the generated pdf and then start making the necessary changes.

**Comment by DanielRuf** [comment]
Hm, but you can still combine both commands in a script to directly create the PDF and start watching the source file.

Both modes should be separate by default imo.

**Comment by Zulko** [comment]
I am a bit torn on this one, my own preference is to not do anything until a file is changed, but I see several people requesting this behavior. I'll change it if it gets more upvotes (maybe also downvote if you are against).

**Comment by Zulko** [comment]
Since the last commit this behaviour is the default.
