### ISSUE TITLE
Document pre-requisites

### ISSUE THREAD

**Issue by stevage** [RelaxedJS/ReLaXed#7]
I was quite surprised to discover that after following the install instructions, and eventually getting to the troubleshooting page, it seems that Chromium is a requirement.

Could I suggest that this (and other pre-reqs) be documented? (Preferable in the "Installing ReLaXed" section...)

**Comment by Zulko** [comment]
In theory in should not be a prerequisite - ReLaXed installs its own Chromium instance via Puppeteer. But in some cases your machine will be lacking some dependencies (which dont prevent ReLaXed installation, but cause problems at run time) so the troubleshooting section suggests asking your system to install chromium as a quick way to get these dependencies.

With which OS did you try and what was the error message ?

**Comment by stevage** [comment]
OIC. It's OSX. Installing according to all the instructions (including npm install) was fine, but at runtime:

```
    throw err;
    ^

Error: Cannot find module 'perf_hooks'
```

**Comment by stevage** [comment]
Seems that perf_hooks is a built in module in later versions of Node, so I'll see if upgrading works. Which brings me back to my original point :) You should document the minimum required version of Node.

**Comment by stevage** [comment]
Upgrading Node to 10.0.0 did solve the problem and I've now got to "hello world" status.

Couple of other observations:

- running 'relaxed' with no arguments produces a stack trace `TypeError: Cannot read property 'substr' of undefined`
- running `relaxed test.pug` doesn't produce a pdf until the source file changes.

**Comment by Zulko** [comment]
Closing this. If other people use a version of Node that doesnt support async I'll add a line in the README. Too laxy to dissect now but i think node 8 should be a minimum requirement.

**Comment by DanielRuf** [comment]
Related https://github.com/RelaxedJS/ReLaXed/issues/30
