### ISSUE TITLE
Expose the require definition to pug renderer

### ISSUE THREAD

**Issue by catc** [RelaxedJS/ReLaXed#71]
Is it possible to import javascript (or json) files into `.pug` documents to use as content?

Something like:
```
// content.js
module.exports = 'some content'

// doc.pug
- var someVal = require('./content.js')
h1 hello world #{someVal}
```

I believe that pug supports it (https://github.com/pugjs/pug/issues/2604#issuecomment-264128999) if you define `require` when passing in variables to pug.

**Comment by Zulko** [comment]
I'd be ok for it (others, any opinion ?). Exposing require should make it easy for users to extend the framework, but when you multiply the "require" it will make rendering slower (since it requires at every run).

Out of curiosity what is your use-case ?

I think I will also make yaml import easy. I like yaml.

**Comment by catc** [comment]
My current use case is:
- i run a script, generate some data - let's say it's json
- my `doc.pug` imports that data, consumes it, builds the pdf
- i run the script again to generate other data, build the pdf with new data
- rinse and repeat

The main benefit would be that you wouldn't have to store your data structures in the pug file, and pug would only contain rendering logic.

**Comment by Zulko** [comment]
This much is clear, the question was more what kind of data, how does it get rendered (table ? graph ?) what kind of document, is it for "interactive" use or use on a server, etc. I'm trying to get ideas of how it could get use, it can influence directions of the software.

**Comment by catc** [comment]
It doesn't have to be rendered in any specific way. The whole point is that users could keep their external data in a separate file, import the raw js/json file and render it. This would help keep your pug file clean of any data/variables.

Another huge benefit of adding exposing `require` is that you would be able to use other npm modules in pug. You could eventually do something like:
```
- var escape = require('lodash/escape')

p An escaped ampersand looks like: #{escape('&')}
```

**Comment by Zulko** [comment]
Done. See [this test example](https://github.com/RelaxedJS/ReLaXed/blob/master/test/samples/data_require_example/master.pug). Note that ReLaXed also exposes ``path`` and ``basedir`` (the directory where the master pug document is). In the example these two constants are used to resolve the path of the local ``data.json``.

**Comment by catc** [comment]
Looks good! Can you get a new build/version out on npm?

**Comment by Zulko** [comment]
possibly this evening

**Comment by catc** [comment]
Thanks!

**Comment by Zulko** [comment]
now in version 0.1.6 on npm
