### ISSUE TITLE
Images inside of #page-header & #page-footer templates

### ISSUE THREAD

**Issue by markheggan** [RelaxedJS/ReLaXed#72]
Is it possible to include images inside of a custom Header or Footer template? Im trying to create a fixed area that repeats on every page, but images don't appear on build, text content is fine…

**Comment by Zulko** [comment]
Unfortunately the header/footer have a lot of limitations (dur to Chromium/Puppeteer) and this may be one of them. One thing I haven't tried is an inline image ``<img src='data:base64;...'>``, maybe it would work. Another way to get something repeated on every page is the CSS ``position: fixed`` but you can't draw in the margins with that. You can also go without margins, but then you don't have page numbers. What is your use case ?

**Comment by markheggan** [comment]
@Zulko Thanks for responding!

I haven't tried `position: fixed`. Would that allow the region to be repeatable on every page?

*Use case** - Custom designed (landscape) invoice document with multiple pages. I wanted to have a fixed sidebar region that will repeat the same information on every page of the invoice.

**Comment by Drew-S** [comment]
So this is an issue that is common from #57 as well. As far as I can tell, puppeteer with its header and footer templates is very limited. Any defined template is across all pages. This prevents front page / other custom page templates, custom numbers, such as a preface having Roman numerals, then the rest being regular number. It also prevents proper footnotes, as for images, I believe it can be done, but only if the data is embedded as @Zulko mentioned.

That being said, I think we can solve this, though it will be difficult. We would need to disable puppeteer  from doing the margins and header / footer template and implement those our selves, I think this is possible, but there are plenty of issues we would have to consider.

**Comment by markheggan** [comment]
Just to give an update on this from my side, `position: fixed` has resolved my own use case, as it does indeed repeat the fixed element on each page of the document.
