### ISSUE TITLE
Acrobat Reader 9.0 rendering issue

### ISSUE THREAD

**Issue by nmihaica** [RelaxedJS/ReLaXed#83]
Rendering is broken on AC 9.0.
Rendering is fine with browsers, SumatraPDF and other software but this one seems to fail.

**Comment by Zulko** [comment]
All ReLaXed does is printing pages with Chromium, so this sounds like a Chromium issue (or an acrobat issue).

Could you tell us more about the rendering issue, maybe post screenshot ?

**Comment by nmihaica** [comment]
Here you go,

Evince on Linux
![evince](https://user-images.githubusercontent.com/12017390/41043598-90dfc7e8-69a4-11e8-9b94-1f20d9a0ac91.gif)

AR 9.0 on Win7
![acrobat](https://user-images.githubusercontent.com/12017390/41043597-90b9ca2a-69a4-11e8-9696-94b6b5243232.gif)

SumatraPDF on Win7
![sumatra](https://user-images.githubusercontent.com/12017390/41043599-910eb8fa-69a4-11e8-88b9-293ee4947962.gif)

**Comment by Zulko** [comment]
oh wow. Have you tried upgrading acrobat to the latest version ?

**Comment by DanielRuf** [comment]
Acrobat 9 is old, the new Acrobat DC / X releases are the current ones.

Keep in mind that Chromium / Chrome generates them so the used PDFX standard / version is nothing that we can control here.

**Comment by Zulko** [comment]
I am closing this, as this seems more a AR9 issue with modern PDFs than a ReLaXed issue. Thanks @nmihaica for the report, and I'd be curious to see if the problem persists in some recent PDF viewers.
