### ISSUE TITLE
page-footer not working

### ISSUE THREAD

**Issue by adrijere** [RelaxedJS/ReLaXed#84]
Hi guys !

First of all, thank you for your amazing work !

I try to implement the page-footer in my pug document as your example : 

```
template#page-footer
  style(type='text/css').
    .pdfheader {
      font-size: 10px;
      font-family: Helvetica;
      font-weight: bold;
      width: 1000px;
      border-top: 1px solid black;
      margin-left: 10%;
      margin-right: 10%;
      padding-top: 1mm;
      margin-bottom: -1mm;
      text-align: center;
    }
  
  .pdfheader Page #[span.pageNumber] / #[span.totalPages]
```

But nothing appears on my pdf and I don't have any errors in my console. I'm on Antergos Linux.

 Do you have any idea ?

Cheers,

**Comment by Zulko** [comment]
Does it work if you run one of the example projects with a footer ?
Also, did you set margins to you page ?

**Comment by adrijere** [comment]
Book and Report examples (so with footer) don't work for me. I don't have the footer on the created pdf.

I set margins on my page yes : 
```
@page {
  margin: 1cm 1cm 2cm 0cm;
}
```

**Comment by Zulko** [comment]
I was able to reproduce and fix it. It must have been broken for a few versions, where the header and footer where exported with the ``template`` tag (which is not displayed). Replacing ``outerHTML`` by ``innerHTML`` did the trick @Drew-S.

This feature is now protected by a test.

It will be github-fixed at my next commit, and npm-fixed at the next release, probably tonight.

**Comment by adrijere** [comment]
Sound good ! Thanks you @Zulko :)

**Comment by Zulko** [comment]
fixed in master, so for next release.

**Comment by Ovski4** [comment]
When is this going to be released?

**Comment by DanielRuf** [comment]
@Ovski4 which version do you use?

**Comment by Ovski4** [comment]
version 0.1.11
I checked on npm it was published 2 months ago so I assume the fix is not in it. Zulko wrote that it must have been broken for a few versions but I don't know which version to use

**Comment by enkos** [comment]
I install relaxed 0.1.6 with `npm i -g relaxedjs@0.1.6`
Check version `relaxed --version`
`> 0.1.6 `
But `template#page-header` and `template#page-footer` still doens't work
`_temp.htm` includes templates but pdf doesn't

**Comment by iJebus** [comment]
Likewise running 0.1.6 and hitting this issue, with my own code and when manually running with the code in https://github.com/RelaxedJS/ReLaXed/tree/master/test/samples/pug/header_and_footer.

**Comment by Zulko** [comment]
I just released a new version (0.2) can you guys give it a try ?

**Comment by enkos** [comment]
I delete old version with `npm r -g relaxedjs`
Install new version `npm i -g relaxedjs@0.2.0`

Then I have tried [this example](https://github.com/RelaxedJS/ReLaXed-examples/blob/master/examples/report/report.pug) and it works. `page-footer` shows in pdf.

But I always need to write styles under the template
```
template#page-header
  style(type='text/css').
    .header {
      font-size: 10px;
    }
  .header I appear at the top of the page
```

Without styles I can't see template. And write styles in scss doesn' help.

[Video example](https://youtu.be/7W13mTK16lY)

**Comment by iJebus** [comment]
It's as @enkos says, but I believe this is an issue with Puppeteer rather than ReLaXed. If you hit up the issues page there, you'll find a pile of issues related to this. 

Maybe this and some of the other caveats should be mentioned in the ReLaXed documentation until Puppeteer is sorted? In their [current form](https://github.com/RelaxedJS/ReLaXed/wiki/Page-formating#page-footer-and-header), the example is broken/incomplete.
