### ISSUE TITLE
DPI setting

### ISSUE THREAD

**Issue by streppelchen** [RelaxedJS/ReLaXed#85]
More of a question than an issue: is there a DPI setting to adjust?
I'm rendering Graphs using the dygraphs library, and the resulting graphs could use a higher DPI in the resulting PDF.

Thanks for the Project!

PS: i can attach a demo pdf is needed.

**Comment by Zulko** [comment]
The DPI setting is not a responsibility of ReLaXed (or Chromium), at least for pictures. Each image has its own resolution when you include them in the page, and they will have the same resolution in the PDF (an original high-quality image will remain high-quality). It seems that dygraph is using Canvas for rendering, so the figure is basically PNG. I have seen that there is an option called pixelRatio in the docs, maybe increasing this could solve your problem ?

**Comment by streppelchen** [comment]
Thanks for your help, it did increase the quality of the resulting graphs in the pdf!
