### ISSUE TITLE
Install does not work

### ISSUE THREAD

**Issue by yv** [RelaxedJS/ReLaXed#9]
Running the installed ReLaXed binary gives an error message (with node 6 as well as node 10):
```
/Users/yannick/sources/ReLaXed/src/index.js:31
async function main () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by Zulko** [comment]
I'm not a Node expert, but this is weird. "async function" should be recognized by modern Node versions. Let's see if others have this problem.

**Comment by yv** [comment]
It turns out Homebrew still had /usr/local/bin/node stuck at Node 6 rather than the Node 10 installed afterwards. Now (after swapping out /usr/local/bin/node) I get a different error.
Since modern is used more restrictively than just "ES2015 modern" it would be nice to explicitly mention that Node >= 8 is required...

**Comment by Zulko** [comment]
what is the new error ?

**Comment by yv** [comment]
Now it's
```
unknown filter ":scss"
```
which seems unrelated

**Comment by DanielRuf** [comment]
Did you reinstall relaxed afterwards?

**Comment by DanielRuf** [comment]
Probably because some force rebuild would be needed as by default the existing directories and files are reused.

**Comment by DanielRuf** [comment]
So this is solved then? Then you can close the issue I guess.
