### ISSUE TITLE
Generating PDF reading HTML from URL

### ISSUE THREAD

**Issue by NyoCon** [RelaxedJS/ReLaXed#91]
Hello,

i just wonder if it's possible to generate a PDF from a Webpage.
In my case we have dynamic HTML templates coming from the backend via http request and I need to generate a PDF from it.

Is it possible to do so?

Greetings

**Comment by Zulko** [comment]
That's a job for puppeteer, just have a look at their README, it's about 6 lines of code to go from a url to a PDF.
