### ISSUE TITLE
Not possible to set meta charset

### ISSUE THREAD

**Issue by upstroke** [RelaxedJS/ReLaXed#92]
I haven't been able to identify where I can set the meta charset. My use case is, that I have to support german umlauts. Guess this will effect any language. So either we need access to the wrapper templates to do so or one of the maintainers could set the meta charset in the html header like so:
```
<head>
  <meta charset="UTF-8">
</head>
```

**Comment by Zulko** [comment]
Thanks, that's a great fix (it also allows utf-8 symbols !). It will be the default in the next releases. If you really need it in the meantime it is doable with the current release, by creating a "local" plugin in your working directory.

In the same folder as your master document, create a file ``my_tweaks.plugin.js``:

```javascript
exports.constructor = async function (params) {
  return {
    headElements: '<meta charset="UTF-8">'
  }
}
```

Then in the same directort a file ``config.yml``:

```yaml
plugins:
  - my_tweaks
```

Let me know if that works for you.

**Comment by upstroke** [comment]
THX @Zulko worked.
