### ISSUE TITLE
How to require json data for use inside pug template?

### ISSUE THREAD

**Issue by upstroke** [RelaxedJS/ReLaXed#93]
Hi there
Maybe I missed it. Is there a possibility to feed "pug" templates with JSON data?

**Comment by Zulko** [comment]
This should work in the latest releases:

```
- var mydata = require(path.join(basedir, 'mylocal.json'))
```

Here the variable ``basedir`` (which is provided by ReLaXed) is the path to the folder ofyour master document.

**Comment by upstroke** [comment]
Hi Zulko
THX, I did not know that I can use the require statement inside of pug templates.
I will try tomorrow.

**Comment by Zulko** [comment]
You can do it because ReLaXed passes ``require`` (and ``path``, and more...) as variables to the pug compiler. Let me know if it worked. In the next versions there should also be a way to pass variables from the command line.

**Comment by upstroke** [comment]
THX @Zulko works.
