### ISSUE TITLE
Control the PDF DPI

### ISSUE THREAD

**Issue by andremacola** [RelaxedJS/ReLaXed#96]
Hi,

I need to export a PDF with at least 300dpi for printing a local magazine. Is it possible with ReLaXed?

Other libraries like mpdf or dompdf has settings like:

`$dompdf->set_option('dpi', 300);`

**Comment by Zulko** [comment]
I don't think Chromium has a DPI option. The idea is that most elements (texts, borders...) are vectorial, and the images always have the same resolution as the file you embedded. Does that answer your question ?
