### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by edirectorios** [RelaxedJS/ReLaXed#97]
Hi, 'im trying to install on la linux mint but it seems not want to be installed.
Below are the final messages aborting the installation

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN relaxedjs@0.1.8 No repository field.
npm ERR! Linux 4.10.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! puppeteer@1.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.5.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the puppeteer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs puppeteer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls puppeteer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/test/engine/relaxed/ReLaXed/npm-debug.log

**Comment by DanielRuf** [comment]
Please try upgrading to Node 10. It also seems you cloned the repository and ran `npm install` there instead of running `npm i relaxed`.

**Comment by DanielRuf** [comment]
Node 4 is very old and reached its EOL.

**Comment by DanielRuf** [comment]
Closing as we did not receive any further feedback.
