### ISSUE TITLE
locals variables not available in npm package

### ISSUE THREAD

**Issue by kexgt** [RelaxedJS/ReLaXed#99]
Hello. I want use --locals parameter, but variable is absent https://npm.runkit.com/relaxedjs/src/masterToPDF.js?t=1530097332998 and https://npm.runkit.com/relaxedjs/src/index.js?t=1530097332998
How I can fixed this issue and used relaxedjs?

**Comment by Zulko** [comment]
I updated the NPM version, please try again.
